from .plot_heatings import plot_heatings
from .plot_currents import plot_currents
from .plot_conductivities import plot_conductivities
from .plot_densities import plot_densities
from .plot_frequencies import plot_frequencies
from .plot_temperatures import plot_temperatures
from .plot_velocities import plot_velocities
from .plot_map_2d import plot_map_2d
from .plot_ortho import plot_ortho
from .plot_polar_north import plot_polar_north
from .plot_polar_south import plot_polar_south
from .plot_quiver import plot_quiver
from .plot_lat_alt import plot_lat_alt